[package]
name = "portfolio-web"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.1"
serde = "1.0.152"
serde_json = "1.0.91"
tokio = { version = "1.24.1", features = ["full"] }
